# frozen_string_literal: true

module Poetry
  module Core
    # Adapted from https://github.com/palkan/view_component-contrib/blob/master/lib/view_component_contrib/translation_helper.rb
    module Contrib
      # Provides internationalization (I18n) support for ViewComponents by managing
      # translation namespaces and scopes.
      #
      # This module enables components to have scoped translations following Rails'
      # I18n conventions, making it easier to organize and manage component-specific
      # translations in your locale files.
      #
      # @example Basic usage
      #   class MyButton::Component < ViewComponent::Base
      #     include Poetry::Core::Contrib::TranslationHelper
      #
      #     def initialize(text: nil)
      #       @text = text
      #     end
      #
      #     def call
      #       content_tag :button, @text || t('.default_text')
      #     end
      #   end
      #
      #   # In your locale file (en.yml):
      #   # en:
      #   #   view_components:
      #   #     my_button:
      #   #       default_text: "Click me"
      #
      # @example Custom namespace
      #   class Admin::Alert::Component < ViewComponent::Base
      #     include Poetry::Core::Contrib::TranslationHelper
      #     self.i18n_namespace = "admin_components"
      #   end
      #
      #   # Translations will be looked up under admin_components.admin.alert
      #
      # @example Custom scope
      #   class Shared::Modal::Component < ViewComponent::Base
      #     include Poetry::Core::Contrib::TranslationHelper
      #     self.i18n_scope = %w[ui modals]
      #   end
      #
      #   # Translations will be looked up under view_components.ui.modals
      module TranslationHelper
        DEFAULT_NAMESPACE = "view_components"

        def self.included(base)
          base.extend ClassMethods
        end

        module ClassMethods
          attr_writer :i18n_namespace

          # Returns the I18n namespace for the component.
          #
          # The namespace is the top-level key under which component translations
          # are organized. If not explicitly set, it inherits from the superclass
          # or defaults to "view_components".
          #
          # @return [String] the I18n namespace
          #
          # @example
          #   class Button::Component < ViewComponent::Base
          #     include Poetry::Core::Contrib::TranslationHelper
          #   end
          #
          #   Button::Component.i18n_namespace
          #   # => "view_components"
          #
          # @example With custom namespace
          #   class Alert::Component < ViewComponent::Base
          #     include Poetry::Core::Contrib::TranslationHelper
          #     self.i18n_namespace = "components"
          #   end
          #
          #   Alert::Component.i18n_namespace
          #   # => "components"
          def i18n_namespace
            return @i18n_namespace if defined?(@i18n_namespace)

            @i18n_namespace =
              if superclass.respond_to?(:i18n_namespace)
                superclass.i18n_namespace
              else
                DEFAULT_NAMESPACE
              end
          end

          # Returns the I18n scope derived from the component's class name.
          #
          # The scope is automatically generated by removing the "::Component" suffix,
          # converting to snake_case, and splitting by "/". This creates a hierarchical
          # path structure for organizing translations.
          #
          # @return [Array<String>] array of scope segments
          #
          # @example
          #   class Admin::Dashboard::Alert::Component < ViewComponent::Base
          #     include Poetry::Core::Contrib::TranslationHelper
          #   end
          #
          #   Admin::Dashboard::Alert::Component.contrib_i18n_scope
          #   # => ["admin", "dashboard", "alert"]
          def contrib_i18n_scope
            return @contrib_i18n_scope if defined?(@contrib_i18n_scope)

            @contrib_i18n_scope = name.sub("::Component", "").underscore.split("/")
          end

          # Sets a custom I18n scope for the component.
          #
          # Use this to override the automatically generated scope with a custom
          # translation path structure.
          #
          # @param val [Array<String>] array of scope segments
          # @raise [ArgumentError] if val is not an Array
          #
          # @example
          #   class MyButton::Component < ViewComponent::Base
          #     include Poetry::Core::Contrib::TranslationHelper
          #     self.i18n_scope = %w[buttons primary]
          #   end
          #
          #   # Translations will be looked up under view_components.buttons.primary
          def i18n_scope=(val)
            raise ArgumentError, "Must be array" unless val.is_a?(Array)

            @contrib_i18n_scope = val.dup.freeze
          end

          # Returns the complete virtual path for I18n lookups.
          #
          # The virtual path combines the namespace and scope into a dot-separated
          # string that represents the full translation key prefix. This is used
          # by Rails' I18n system to look up translations.
          #
          # @return [String] the complete virtual path
          #
          # @example
          #   class Admin::Alert::Component < ViewComponent::Base
          #     include Poetry::Core::Contrib::TranslationHelper
          #   end
          #
          #   Admin::Alert::Component.virtual_path
          #   # => "view_components.admin.alert"
          #
          # @example With custom namespace and scope
          #   class Modal::Component < ViewComponent::Base
          #     include Poetry::Core::Contrib::TranslationHelper
          #     self.i18n_namespace = "ui"
          #     self.i18n_scope = %w[dialogs modal]
          #   end
          #
          #   Modal::Component.virtual_path
          #   # => "ui.dialogs.modal"
          def virtual_path
            @virtual_path ||= [
              i18n_namespace,
              *contrib_i18n_scope
            ].join(".")
          end
        end
      end
    end
  end
end
