# frozen_string_literal: true

module Poetry
  module Core
    module CSS
      # Generates the Tailwind safelist: every utility class poetry's Style
      # dictionaries emit, one per line. This solves the consumer-purge
      # problem: a host app's Tailwind build can't see classes resolved at
      # render time in Ruby, so the generated safelist file is added to the
      # host's `@source` paths and every dictionary class survives the build.
      #
      # Template-static classes (from .html.erb sidecars) are extracted via
      # the Herb AST and included too - see {TemplateClasses}.
      #
      # @example
      #   Poetry::Core::CSS::Safelist.new(style_classes: [MyApp::Button::Style]).text
      #   # => "# poetry Tailwind safelist ...\nbg-primary\ninline-flex\n..."
      #
      # @api private
      class Safelist
        HEADER = "# poetry Tailwind safelist - generated by `bin/rake css:safelist`; add to @source. DO NOT EDIT."

        # @param style_classes [Enumerable<Class>] Style subclasses to collect from
        # @param template_classes [Enumerable<String>] extra (template-static) classes
        def initialize(style_classes:, template_classes: [])
          @style_classes = style_classes
          @template_classes = template_classes
        end

        def classes
          dictionary = @style_classes.flat_map { |style| style.resolver.all_classes }
          (dictionary + @template_classes.to_a).uniq.sort
        end

        def text
          "#{([HEADER] + classes).join("\n")}\n"
        end
      end
    end
  end
end
