# frozen_string_literal: true

require "test_helper"

module Poetry
  module Core
    # The host application's own components: discovered by convention
    # (under the app root, outside the gem namespace, published), carrying
    # their declared helper into the registry, and readable boot-free.
    class HostComponentsTest < Minitest::Test
      FIXTURE_ROOT = Pathname.new(File.expand_path("../../fixtures/host_app", __dir__))

      # Loaded once from the fixture tree (no autoloader covers it), so
      # const_source_location points under FIXTURE_ROOT/app.
      def self.load_fixtures!
        return if defined?(Demo::Badge::Component)

        Dir.glob(FIXTURE_ROOT.join("app/components/**/*.rb").to_s).each { |file| load file }
      end

      def setup
        self.class.load_fixtures!
      end

      def test_select_keeps_published_components_outside_the_gem_namespace
        selected = HostComponents.select(Poetry::Core::Component.descendants)

        assert_includes selected.map(&:name), "Demo::Badge::Component"
        refute_includes selected, Poetry::Core::CopiedProbe::Component, "a copy under the gem namespace is the gem's"
        refute_includes selected, Demo::Badge::Item, "internal components have no entry"
        assert(selected.none? { |component| component.component_path.start_with?("poetry/") })
      end

      def test_discover_loads_every_managed_components_directory_and_selects
        assert_includes HostComponents.discover.map(&:name), "Demo::Badge::Component"
      end

      def test_registry_carries_the_declared_helper_and_the_contract
        registry = HostComponents.registry(root: FIXTURE_ROOT)
        entry = registry.entries.fetch("demo/badge")

        assert_equal "demo_badge", entry["helper"]
        assert_equal ["Demo badges are read-only labels; never attach click handlers."], entry["agent_rules"]
        assert_equal %w[neutral loud], entry["styles"].find { |style| style["name"] == "tone" }["variants"]
        assert_equal({ "demo_badge" => 0 }, registry.helper_args, "factory helpers take keywords only")
        assert_equal FIXTURE_ROOT, registry.source_root
      end

      def test_committed_state_tracks_the_app_registry_file
        Dir.mktmpdir do |root|
          assert_equal :missing, HostComponents.committed_state(root: root)
          path = HostComponents.registry(root: root).generate!

          assert_equal :fresh, HostComponents.committed_state(root: root)
          assert_includes path.read, "generated by `bin/rails poetry:registry`"
          path.write("#{path.read}\n# edited\n")

          assert_equal :stale, HostComponents.committed_state(root: root)
        end
      end

      def test_declared_helpers_reads_the_source_without_loading
        assert_equal ["demo_badge"], HostComponents.declared_helpers(root: FIXTURE_ROOT)
      end

      def test_helper_macro_validates_the_name_and_is_own_class_only
        assert_raises(ArgumentError) { Class.new(Poetry::Core::Component) { helper :"bad-name" } }
        assert_nil Class.new(Demo::Badge::Component).helper_name, "a subclass declares its own or has none"
        assert_equal "demo_badge", Demo::Badge::Component.helper_name
      end
    end

    # The engine-defined view helpers for those components.
    class HostHelpersTest < Minitest::Test
      FIXTURE_ROOT = HostComponentsTest::FIXTURE_ROOT

      View = Class.new do
        include Poetry::Core::HostHelpers

        attr_reader :rendered

        def render(component, &block)
          @rendered = [component, block]
          "rendered"
        end
      end

      def setup
        HostComponentsTest.load_fixtures!
      end

      def teardown
        HostHelpers.sync!([])
      end

      def test_sync_defines_a_keyword_helper_that_renders_the_class_by_name
        assert_equal ["demo_badge"], HostHelpers.sync!([Demo::Badge::Component])

        view = View.new
        result = view.demo_badge(tone: :loud) { "New" }
        component, block = view.rendered

        assert_equal "rendered", result
        assert_instance_of Demo::Badge::Component, component
        assert_equal :loud, component.tone
        assert_equal "New", block.call
      end

      def test_sync_removes_helpers_no_longer_declared
        HostHelpers.sync!([Demo::Badge::Component])
        HostHelpers.sync!([])

        refute_respond_to View.new, :demo_badge
        assert_empty HostHelpers.owned
      end

      module TwinA
        class Component < Poetry::Core::Component
          helper :twin

          def call = "a"
        end
      end

      module TwinB
        class Component < Poetry::Core::Component
          helper :twin

          def call = "b"
        end
      end

      module PrivateClashProbe
        class Component < Poetry::Core::Component
          helper :format

          def call = "f"
        end
      end

      def test_two_components_declaring_one_helper_raise_naming_both
        error = assert_raises(Poetry::Core::Error) { HostHelpers.sync!([TwinA::Component, TwinB::Component]) }

        assert_match(/TwinB::Component and .*TwinA::Component both declare helper :twin/, error.message)
        refute_includes HostHelpers.owned, "twin"
      end

      def test_a_private_view_method_counts_as_taken
        error = assert_raises(Poetry::Core::Error) { HostHelpers.sync!([PrivateClashProbe::Component]) }

        assert_match(/helper :format, but a view helper named format already exists \(Action View\)/, error.message)
      end

      def test_the_app_s_own_helpers_count_as_taken
        helpers = Module.new { def demo_badge = "shadow" }
        controller = Class.new { define_singleton_method(:_helpers) { helpers } }
        Object.const_set(:ApplicationController, controller)
        error = assert_raises(Poetry::Core::Error) { HostHelpers.sync!([Demo::Badge::Component]) }

        assert_match(/named demo_badge already exists \(the app's helpers\)/, error.message)
      ensure
        Object.send(:remove_const, :ApplicationController) if Object.const_defined?(:ApplicationController, false)
      end

      def test_a_clash_leaves_nothing_half_defined_and_the_next_sync_recovers
        HostHelpers.sync!([])
        assert_raises(Poetry::Core::Error) { HostHelpers.sync!([Demo::Badge::Component, ClashProbe::Component]) }

        assert_empty HostHelpers.owned, "nothing was defined before the clash raised"
        refute_respond_to View.new, :demo_badge
        assert_equal ["demo_badge"], HostHelpers.sync!([Demo::Badge::Component]), "the reload after the fix is clean"
      ensure
        HostHelpers.sync!([])
      end

      def test_declared_helpers_parses_rather_than_greps
        Dir.mktmpdir do |root|
          dir = File.join(root, "app/components/acme/pill")
          FileUtils.mkdir_p(dir)
          File.write(File.join(dir, "component.rb"), <<~RUBY)
            module Acme::Pill
              # helper :in_a_comment
              class Component < Poetry::Core::Component
                helper(:parenthesised)
                self.helper "as_string"
                DOC = <<~MD
                  helper :in_a_heredoc
                MD
                def call = "helper :in_a_string"
              end
            end
            helper :outside_any_class
          RUBY

          assert_equal %w[as_string parenthesised], HostComponents.declared_helpers(root: root)
        end
      end

      # A named probe (an anonymous class with a stubbed name would sit in
      # `descendants` with a constant that resolves to nothing).
      module ClashProbe
        class Component < Poetry::Core::Component
          helper :render

          def call
            content_tag(:span, content)
          end
        end
      end

      def test_a_name_already_taken_by_a_view_helper_raises
        error = assert_raises(Poetry::Core::Error) { HostHelpers.sync!([ClashProbe::Component]) }
        assert_match(/helper :render, but a view helper named render already exists/, error.message)
      end
    end
  end
end
