# frozen_string_literal: true

module Poetry
  module Core
    # The host application's own components - its own and its engines' -
    # written on the Poetry DSL (never the gems' copies, which `poetry:add`
    # places under the gem namespace and the gem registries already
    # describe). Discovery is convention, not configuration: every
    # published Component descendant whose path does not start with
    # `poetry/`, after every components directory the autoloader manages
    # has been loaded. The class names its view helper with `helper :name`;
    # the engine defines that helper on Action View at boot and on every
    # reload, and the booted surfaces (`poetry:check`, llms.txt, the
    # generated skill) read the app's registry built here.
    #
    # @example
    #   Poetry::Core::HostComponents.registry(root: Rails.root).entries.keys # => ["demo/badge"]
    #
    # @api private
    module HostComponents
      # Paths under this prefix belong to a poetry gem (or a copy of one).
      GEM_PREFIX = "poetry/"
      # The `helper :name` declaration, as source text - the boot-free
      # read (the MCP server's check tool) scans component files for it.
      DECLARATION = /^\s*helper\s+:([a-z_][a-z0-9_]*)\b/
      # The committed app registry's banner (a gem's names its rake task).
      BANNER = <<~HEADER
        # poetry app component registry - generated by `bin/rails poetry:registry` from app/components.
        # DO NOT EDIT: `bin/rails poetry:verify` fails when this file is stale; `poetry:check` warns.
      HEADER

      module_function

      # Every app component class, loaded. Each components directory the
      # main autoloader manages (the app's and every engine's) is
      # eager-loaded first: `descendants` sees only loaded classes, and lazy
      # autoloading would otherwise make the set depend on which views
      # rendered so far. Without an autoloader the caller loads the files.
      #
      # @return [Array<Class>]
      def discover
        if (loader = defined?(Rails) && Rails.respond_to?(:autoloaders) && Rails.autoloaders.main)
          loader.dirs.grep(%r{/app/components\z}).each { |dir| loader.eager_load_dir(dir) }
        end
        select(Poetry::Core::Component.descendants)
      end

      # The app's own components among `components`: named, published (not
      # internal), outside the gem namespace.
      #
      # @param components [Enumerable<Class>]
      # @return [Array<Class>] sorted by name
      def select(components)
        components.select(&:name).reject(&:internal_component)
                  .reject { |component| component.component_path.start_with?(GEM_PREFIX) }
                  .sort_by(&:name)
      end

      # The app's registry, built live from its loaded classes - the same
      # entry contract as a gem registry (options, styles, parts, agent
      # rules, wiring), plus the declared helper per entry. Helpers the
      # engine defines take keywords only, so the arity map says so and
      # `poetry check` flags a positional argument.
      #
      # @param root [String, Pathname] the app root
      # @return [Registry]
      def registry(root:)
        components = discover
        helper_args = components.filter_map { |component| [component.helper_name, 0] if component.helper_name }.to_h
        Registry.new(components: components, source_root: root, helper_args: helper_args, banner: BANNER)
      end

      # The committed app registry (`bin/rails poetry:registry` writes it to
      # the same path a gem's registry lives at, so boot-free consumers -
      # the MCP server - find the app's components the way they find a
      # gem's) against the live build: :missing (never written; the app
      # opted out of the boot-free surfaces), :fresh, or :stale (written,
      # then the components changed - `poetry:check` warns, `poetry:verify`
      # fails).
      #
      # @param root [String, Pathname] the app root
      # @return [Symbol] :missing, :fresh, or :stale
      def committed_state(root:)
        path = Pathname.new(root).join(Registry::RELATIVE_PATH)
        return :missing unless path.exist?

        path.read == registry(root: root).to_yaml ? :fresh : :stale
      end

      # The declared helper names, boot-free: a source scan of the app's
      # component files for `helper :name`, for consumers that never load
      # the classes (the MCP server's check tool, which runs without
      # Rails). The booted surfaces read {.registry} instead.
      #
      # @param root [String, Pathname] the app root
      # @return [Array<String>] sorted, unique
      def declared_helpers(root:)
        Dir.glob(Pathname.new(root).join("app/components/**/*.rb").to_s).flat_map do |file|
          File.read(file).scan(DECLARATION).flatten
        end.uniq.sort
      end
    end
  end
end
