# frozen_string_literal: true

require "yaml"

module Poetry
  module Core
    # The generated component registry: the machine-readable index of
    # every component's public surface, built entirely FROM SOURCE - the
    # prop_definitions introspection shim + the Style dictionaries -
    # and CI-verified against a fresh build (the upstream
    # convergence: a committed registry that can never drift from the code).
    #
    # Consumers: the docs site, the MCP server, the agent skill, and
    # the A2UI / WebMCP projections - one contract, every surface.
    class Registry
      HEADER = <<~HEADER
        # poetry component registry - generated by `bin/rake registry:generate` FROM SOURCE.
        # DO NOT EDIT: CI verifies this file matches a fresh build (rake registry:verify).
      HEADER

      RELATIVE_PATH = "config/component_registry.yml"

      # Stimulus lifecycle callbacks are not consumer-callable actions.
      LIFECYCLE_METHODS = %w[connect disconnect initialize].freeze

      # @param components [Enumerable<Class>, nil] component classes; defaults
      #   to every named Poetry::Core::Component descendant (eager-loaded)
      #   whose source lives under source_root.
      # @param source_root [Pathname, String] the gem root to discover in and
      #   write the registry to - poetry-ui passes its own root.
      def initialize(components: nil, source_root: Poetry::Core.root)
        @source_root = Pathname.new(source_root)
        @components = (components || discover).sort_by(&:name)
      end

      # The discovered component classes (the registry's working set).
      attr_reader :components

      def entries
        @components.to_h { |component| [component.component_path, entry_for(component)] }
      end

      def to_yaml
        HEADER + YAML.dump({ "components" => entries })
      end

      def generate!(root: @source_root)
        path = Pathname.new(root).join(RELATIVE_PATH)
        path.dirname.mkpath
        path.write(to_yaml)
        path
      end

      # False when the committed registry does not match a fresh build.
      def verified?(root: @source_root)
        path = Pathname.new(root).join(RELATIVE_PATH)
        path.exist? && path.read == to_yaml
      end

      private

      # Named Component descendants whose source lives inside source_root's
      # app/ tree - excludes host-app AND test-defined components, so
      # discovery is identical under a fresh boot and inside the test suite.
      # The components dir is eager-loaded first: `descendants` only sees
      # loaded classes, and lazy autoloading (tests) would otherwise make
      # discovery order-dependent.
      def discover
        app_root = @source_root.join("app")
        components_dir = app_root.join("components")
        if defined?(Rails) && Rails.respond_to?(:autoloaders) && components_dir.directory?
          Rails.autoloaders.main.eager_load_dir(components_dir)
        end
        Poetry::Core::Component.descendants.select(&:name).select do |component|
          path = Object.const_source_location(component.name)&.first
          path&.start_with?(app_root.to_s)
        end
      end

      def entry_for(component)
        props = component.prop_definitions
        entry = {
          "class_name" => component.name,
          "identifier" => component.component_identifier,
          "bem_block" => component.component_path.tr("/", "-"),
          "styles" => plain(props[:styles]),
          "options" => plain(props[:options]),
          "slots" => plain(props[:slots])
        }
        if (style = component.style_class)
          entry["elements"] = style.resolver.elements.keys.map(&:to_s)
          entry["capsule"] = style.capsule
        end
        # The JS wiring surface (N7 W1): the poetry--core--* controller
        # identifiers the component wires, each joined to its manifest
        # (targets / values / actions) so the registry is the ONE contract
        # poetry check / llms.txt / the MCP server read. Derived from the
        # component's controller-identifier constants (%i[poetry core x]);
        # the rendered-truth drift test guarantees this equals what the
        # previews actually emit as data-controller.
        # plain() rebuilds fresh objects - the manifest arrays are shared
        # across components that wire the same controller (popper is in 8),
        # which would otherwise make Psych emit YAML anchors/aliases.
        controllers = wired_controllers(component)
        entry["controllers"] = plain(controllers) unless controllers.empty?
        # Component-specific constraints agents must honor (the contract's
        # agent_rules section) - declared as an AGENT_RULES constant.
        entry["agent_rules"] = component::AGENT_RULES.dup if component.const_defined?(:AGENT_RULES)
        entry
      end

      # The controller-identifier constants a component defines/inherits
      # (Sheet reuses Dialog's), formatted to identifiers and joined to the
      # manifest. A constant qualifies when its value is an array of symbols
      # beginning [:poetry, :core, ...] - exactly the Builder identifier shape.
      def wired_controllers(component)
        # Constants live inconsistently: some components define them on the
        # Component class (Checkbox::CHECKED), others on the enclosing module
        # (Select::SELECT/POPPER), and subclasses inherit them (Sheet reuses
        # Dialog's). Scan the class (+ ancestors) AND the component's module,
        # then let the rendered-truth drift test arbitrate.
        scopes = [component]
        scopes << component.module_parent if component.respond_to?(:module_parent)

        identifiers = scopes.flat_map do |scope|
          own = scope.equal?(component) # inherited only matters for the class
          scope.constants(own).filter_map do |name|
            value = scope.const_get(name)
            next unless value.is_a?(Array) && value.all?(Symbol) && value.first(2) == %i[poetry core]

            Poetry::Core::Stimulus::Builder.format_identifier(value)
          rescue StandardError
            next
          end
        end

        identifiers.uniq.sort.map do |identifier|
          definition = Poetry::Core::Stimulus::Manifest.catalog[identifier] || {}
          {
            "identifier" => identifier,
            "targets" => definition["targets"] || [],
            "values" => (definition["values"] || {}).keys.sort,
            "actions" => (definition["methods"] || []) - LIFECYCLE_METHODS
          }
        end
      end

      # Deep-converts symbols to strings so the YAML is plain data (no
      # !ruby/symbol tags) - loadable by any consumer, any language.
      def plain(value)
        case value
        when Hash then value.to_h { |k, v| [k.to_s, plain(v)] }
        when Array then value.map { |v| plain(v) }
        when Symbol then value.to_s
        else value
        end
      end
    end
  end
end
