# frozen_string_literal: true

require "yaml"

module Poetry
  module Core
    # The generated component registry: the machine-readable index of
    # every component's public surface, built entirely FROM SOURCE - the
    # prop_definitions introspection shim + the Style dictionaries -
    # and CI-verified against a fresh build (a committed registry that
    # can never drift from the code).
    #
    # Consumers: the docs site, the MCP server, the agent skill, and
    # the A2UI / WebMCP projections - one contract, every surface.
    #
    # @example Generate the registry for a gem root
    #   Poetry::Core::Registry.new(source_root: gem_root).generate!
    class Registry
      # The banner written at the top of the generated YAML.
      HEADER = <<~HEADER
        # poetry component registry - generated by `bin/rake registry:generate` FROM SOURCE.
        # DO NOT EDIT: CI verifies this file matches a fresh build (rake registry:verify).
      HEADER

      # Where the committed registry lives, relative to a gem root.
      RELATIVE_PATH = "config/component_registry.yml"

      # Stimulus lifecycle callbacks are not consumer-callable actions.
      LIFECYCLE_METHODS = %w[connect disconnect initialize].freeze

      # The id-minting funnel, as source text: a component family whose
      # sources never match renders no poetry-minted random id (the
      # "identity" derivation - see the entry's identity key).
      MINT_PATTERN = /\bpoetry_instance_id\b|\binstance_id\b|\bSecureRandom\b/

      # The committed-registry view: the four generated sections
      # plus the root they resolve against, read straight from the YAML a
      # `registry:generate` run committed - no component classes, no Rails.
      # It satisfies every LlmsText/SkillText read (entries / blocks /
      # source_root), so boot-free consumers (the MCP server, runtime skill
      # delivery) share one loader instead of each parsing the payload.
      class Committed
        attr_reader :entries, :blocks, :helpers, :helper_args, :form_builder, :source_root

        # Holds the sections of one committed registry file;
        # {Registry.committed} is the loader.
        #
        # @param entries [Array<Hash>] the "components" section
        # @param blocks [Array<Hash>, nil] the "blocks" section
        # @param helpers [Hash, nil] the "helpers" section
        # @param helper_args [Hash, nil] the "helper_args" section
        # @param source_root [Pathname] the gem root the paths resolve against
        # @param form_builder [Hash, nil] the "form_builder" section
        def initialize(entries:, blocks:, helpers:, helper_args:, source_root:, form_builder: nil)
          @form_builder = form_builder
          @entries = entries
          @blocks = blocks
          @helpers = helpers
          @helper_args = helper_args
          @source_root = source_root
        end
      end

      # Loads the committed registry YAML boot-free.
      #
      # @param root [String, Pathname] the gem root holding the registry file
      # @return [Committed]
      def self.committed(root)
        source_root = Pathname.new(root)
        payload = YAML.load_file(source_root.join(RELATIVE_PATH), aliases: true)
        Committed.new(entries: payload.fetch("components"), blocks: payload["blocks"],
                      helpers: payload["helpers"], helper_args: payload["helper_args"],
                      form_builder: payload["form_builder"], source_root: source_root)
      end

      # @param components [Enumerable<Class>, nil] component classes; defaults
      #   to every named Poetry::Core::Component descendant (eager-loaded)
      #   whose source lives under source_root.
      # @param source_root [Pathname, String] the gem root to discover in and
      #   write the registry to - poetry-ui passes its own root.
      # @param helpers [Hash, nil] wrapper helpers that are NOT components
      #   (poetry_input_group_addon et al): helper name => contract hash
      #   ({"options" => [...]}, or {} for a plain wrapper). Emitted as the
      #   registry's "helpers" section so boot-free consumers (poetry check,
      #   the MCP server) know the full valid helper set AND the value
      #   contracts runtime-enforced inside those helpers.
      # @param blocks [Hash, nil] the gem's block catalog: block
      #   name => {"title", "description", "components", "template"} - title/
      #   description parsed from each template's poetry:block header, the
      #   composed components derived from its poetry_* calls, template the
      #   gem-relative source path boot-free consumers (the MCP server) read.
      #   Emitted as the registry's "blocks" section.
      # @param helper_args [Hash, nil] max POSITIONAL arity per poetry_*
      #   helper, introspected from the gem's helper-module signatures
      #   (e.g. `poetry_link "text", href:` on a kwargs-only
      #   helper raises at render). Rest-signatures are omitted (unknowable); the linter
      #   enforces arity only where a key exists, so registries without the
      #   map stay lint-identical.
      # @param descriptions [Hash, nil] one-line human descriptions per
      #   component_path (the gem's editorial component_descriptions.yml),
      #   merged into each entry as "description" - the summary llms.txt, the
      #   MCP describe_component, and the docs page all read from one source.
      # @param form_builder [Hash, nil] the gem's FormBuilder surface
      #   ({"rules" => [...], "methods" => {name => one-liner}, "input_types"
      #   => [...]}) - emitted as the registry's "form_builder" section so
      #   llms.txt, the MCP server, and skills can teach the model-bound
      #   form story without booting the gem. Optional like every other
      #   section: absent -> the registry stays byte-identical.
      def initialize(components: nil, source_root: Poetry::Core.root, # rubocop:disable Metrics/ParameterLists
                     helpers: nil, blocks: nil, helper_args: nil, descriptions: nil, form_builder: nil)
        @source_root = Pathname.new(source_root)
        @components = (components || discover).sort_by(&:name)
        @helpers = helpers
        @blocks = blocks
        @helper_args = helper_args
        @descriptions = descriptions
        @form_builder = form_builder
      end

      # The discovered component classes (the registry's working set).
      attr_reader :components

      # The block catalog and the root template paths resolve against -
      # LlmsText reads both to inline block source into llms-full.txt.
      attr_reader :blocks, :source_root

      # The FormBuilder surface (optional section) - LlmsText renders it as
      # the Forms section.
      attr_reader :form_builder

      # The full registry payload's "components" section: one contract hash
      # per discovered component, keyed by component path.
      #
      # @return [Hash{String => Hash}]
      def entries
        @components.to_h { |component| [component.component_path, entry_for(component)] }
      end

      # The complete registry serialized as plain-data YAML (components plus
      # the optional helpers/blocks/helper_args/form_builder sections),
      # headed by the do-not-edit banner.
      #
      # @return [String]
      def to_yaml
        payload = { "components" => entries }
        payload["helpers"] = plain(@helpers.sort.to_h) if @helpers&.any?
        payload["blocks"] = plain(@blocks.sort.to_h) if @blocks&.any?
        payload["helper_args"] = plain(@helper_args.sort.to_h) if @helper_args&.any?
        payload["form_builder"] = plain(@form_builder) if @form_builder&.any?
        HEADER + YAML.dump(payload)
      end

      # Writes the registry YAML to its committed location under root.
      #
      # @param root [Pathname, String] the gem root to write under
      # @return [Pathname] the written file path
      def generate!(root: @source_root)
        path = Pathname.new(root).join(RELATIVE_PATH)
        path.dirname.mkpath
        path.write(to_yaml)
        path
      end

      # False when the committed registry does not match a fresh build.
      #
      # @param root [Pathname, String] the gem root holding the committed file
      # @return [Boolean]
      def verified?(root: @source_root)
        path = Pathname.new(root).join(RELATIVE_PATH)
        path.exist? && path.read == to_yaml
      end

      private

      # Named Component descendants whose source lives inside source_root's
      # app/ tree - excludes host-app AND test-defined components, so
      # discovery is identical under a fresh boot and inside the test suite.
      # The components dir is eager-loaded first: `descendants` only sees
      # loaded classes, and lazy autoloading (tests) would otherwise make
      # discovery order-dependent.
      def discover
        app_root = @source_root.join("app")
        components_dir = app_root.join("components")
        if defined?(Rails) && Rails.respond_to?(:autoloaders) && components_dir.directory?
          Rails.autoloaders.main.eager_load_dir(components_dir)
        end
        Poetry::Core::Component.descendants.select(&:name).reject(&:internal_component).select do |component|
          path = Object.const_source_location(component.name)&.first
          path&.start_with?(app_root.to_s)
        end
      end

      # Whether the component's rendered output can carry a poetry-minted
      # id. An IDENTITY constant declared on the component's own ancestry
      # wins (composition: a component whose DOM carries ids minted by
      # components it RENDERS derives false and declares true). Otherwise
      # the ancestor chain below Poetry::Core::Component - the class
      # itself, family modules, intermediate bases; everywhere minting
      # calls live - is source-scanned for the poetry_instance_id funnel
      # (or a direct SecureRandom mint). The walk stops at the base class
      # so the funnel's own definition never reads as a call, and the
      # scan errs toward true: a false positive keeps a warning, a false
      # negative would silence a real one.
      def mints_identity?(component)
        family = component.ancestors.take_while { |mod| mod != Poetry::Core::Component }
        override = family.find { |mod| mod.const_defined?(:IDENTITY, false) }
        return override.const_get(:IDENTITY, false) if override

        family.any? { |mod| mint_source?(mod) }
      end

      # Whether one ancestor's source file mentions the minting funnel.
      def mint_source?(mod)
        path = mod.name && Object.const_source_location(mod.name)&.first
        return false unless path && File.exist?(path)

        mint_sources = (@mint_sources ||= {})
        mint_sources.fetch(path) { mint_sources[path] = File.read(path).match?(MINT_PATTERN) }
      end

      def entry_for(component)
        props = component.prop_definitions
        entry = {
          "class_name" => component.name,
          "identifier" => component.component_identifier,
          "bem_block" => component.component_path.tr("/", "-"),
          "styles" => plain(props[:styles]),
          "options" => plain(props[:options]),
          "slots" => plain(props[:slots])
        }
        # The one-line human description (editorial, merged from the gem's
        # component_descriptions.yml) - the summary llms.txt / describe_component
        # / the docs page read from this single source.
        if @descriptions && (description = @descriptions[component.component_path])
          entry["description"] = description
        end
        # Hand-rolled with_* conveniences beyond the registered slots
        # (NavigationMenu#with_link) - consumers call them, so check and the
        # agent surfaces must know them.
        entry["slot_extras"] = plain(props[:slot_extras]) if props[:slot_extras]&.any?
        if (style = component.style_class)
          entry["elements"] = style.resolver.elements.keys.map(&:to_s)
          entry["capsule"] = style.capsule
        end
        # The JS wiring surface: the poetry--core--* controller
        # identifiers the component wires, each joined to its manifest
        # (targets / values / actions) so the registry is the ONE contract
        # poetry check / llms.txt / the MCP server read. Derived from the
        # component's controller-identifier constants (%i[poetry core x]);
        # the rendered-truth drift test guarantees this equals what the
        # previews actually emit as data-controller.
        # plain() rebuilds fresh objects - the manifest arrays are shared
        # across components that wire the same controller (popper is in 8),
        # which would otherwise make Psych emit YAML anchors/aliases.
        controllers = wired_controllers(component)
        entry["controllers"] = plain(controllers) unless controllers.empty?
        # Component-specific constraints agents must honor (the contract's
        # agent_rules section) - declared as an AGENT_RULES constant.
        entry["agent_rules"] = component::AGENT_RULES.dup if component.const_defined?(:AGENT_RULES)
        # The requires_content declaration:
        # the same fact that raises at render lets poetry check flag a
        # blockless call statically.
        if component.respond_to?(:required_content) && (hint = component.required_content)
          entry["requires_content"] = hint
        end
        # The REQUIRED_SLOTS declaration: the
        # same fact that raises in before_render lets poetry check flag a
        # call that never sets the slot, statically.
        entry["required_slots"] = plain(props[:required_slots]) if props[:required_slots]&.any?
        # The REQUIRES_ANY declaration: the conditional any-of
        # contracts - the before_render disjunction, stated statically.
        entry["requires_any"] = plain(props[:requires_any]) if props[:requires_any]&.any?
        # The identity fact: false when the family renders no
        # poetry-minted id - key:/id: would have nothing to stabilize, so
        # check's stable-identity rules skip the helper. Absent = the
        # component mints (legacy registries keep every warning).
        entry["identity"] = false unless mints_identity?(component)
        # The part contract: the
        # styling surface - data-slot parts, state attributes per part,
        # CSS var seams - hand-authored prose that PartContract.verify
        # holds to the rendered DOM of every preview.
        parts = component.part_definitions
        entry["parts"] = plain(parts) if parts.any?

        # The element-level wiring projection (use_stimulus declarations,
        # resolved): which parts carry which controllers, values, actions,
        # and targets - the usage view beside the controllers section's
        # capability view.
        if component.respond_to?(:stimulus_definitions)
          wiring = component.stimulus_definitions
          entry["stimulus"] = plain(wiring) if wiring.any?
        end
        # The agent-tool projection (tool declarations, MCP Tool-shaped):
        # the component's operate surface - what an in-page agent may
        # invoke on a rendered instance, and which Stimulus action each
        # tool dispatches.
        if component.respond_to?(:tool_definitions)
          tools = component.tool_definitions
          entry["tools"] = plain(tools) if tools.any?
        end
        entry
      end

      # The controllers a component wires, joined to the manifest. Two
      # sources: use_stimulus declarations (exact - the resolved
      # identifiers of every declared element) and, for components not yet
      # migrated to declarations, the legacy constant scan - an array of
      # symbols beginning [:poetry, :core, ...] is exactly the Builder
      # identifier shape.
      def wired_controllers(component)
        identifiers = []
        if component.respond_to?(:stimulus_identifiers)
          # Manifest-known only: host-app controllers declared by a
          # component are not poetry's to document.
          identifiers += component.stimulus_identifiers
                                  .select { |id| Poetry::Core::Stimulus::Manifest.catalog.key?(id) }
        end

        # Constants live inconsistently: some components define them on the
        # Component class (Checkbox::CHECKED), others on the enclosing module
        # (Select::SELECT/POPPER), and subclasses inherit them (Sheet reuses
        # Dialog's). Scan the class (+ ancestors) AND the component's module,
        # then let the rendered-truth drift test arbitrate.
        scopes = [component]
        scopes << component.module_parent if component.respond_to?(:module_parent)

        identifiers += scopes.flat_map do |scope|
          own = scope.equal?(component) # inherited only matters for the class
          scope.constants(own).filter_map do |name|
            value = scope.const_get(name)
            next unless value.is_a?(Array) && value.all?(Symbol) && value.first(2) == %i[poetry core]

            Poetry::Core::Stimulus::Builder.format_identifier(value)
          rescue StandardError
            next
          end
        end

        identifiers.uniq.sort.map do |identifier|
          definition = Poetry::Core::Stimulus::Manifest.catalog[identifier] || {}
          {
            "identifier" => identifier,
            "targets" => definition["targets"] || [],
            "values" => (definition["values"] || {}).keys.sort,
            "actions" => (definition["methods"] || []) - LIFECYCLE_METHODS,
            "events" => definition["events"] || []
          }
        end
      end

      # Deep-converts symbols to strings so the YAML is plain data (no
      # !ruby/symbol tags) - loadable by any consumer, any language.
      def plain(value)
        case value
        when Hash then value.to_h { |k, v| [k.to_s, plain(v)] }
        when Array then value.map { |v| plain(v) }
        when Symbol then value.to_s
        else value
        end
      end
    end
  end
end
