# frozen_string_literal: true

require "yaml"

module Poetry
  module Core
    class Tokens
      # Generates every downstream token surface from tokens/tokens.dtcg.json
      # (the single source of truth):
      #
      # tokens/tokens.css CSS custom properties (root +.dark)
      #   tokens/tailwind-theme.css  Tailwind v4 @theme inline mapping
      #   DESIGN.md                  front matter regenerated; prose body preserved
      #
      # `verify` powers the CI drift gate (rake tokens:verify): committed
      # artifacts must byte-match a fresh generation, so the canonical JSON
      # and the shipped CSS/DESIGN.md can never disagree.
      class Generator
        HEADER = "Generated by `bin/rake tokens:generate` from tokens/tokens.dtcg.json - DO NOT EDIT BY HAND."

        # Documented divergences from the shadcn/ui v4 neutral theme. Parity
        # is the default; a delta is only taken when the locked AA floor
        # demands it, and it must be recorded here.
        PARITY_DELTAS = [
          "light muted-foreground: oklch(0.545 0 0) vs shadcn's 0.556 - darkened to clear the locked WCAG AA " \
          "floor (4.54:1 on muted, 4.96:1 on background; shadcn's own value is 4.34:1 on muted, sub-AA)."
        ].freeze

        # The distributed shadcn v4 radius scale (@theme inline).
        RADIUS_SCALE = {
          "sm" => "calc(var(--radius) - 4px)",
          "md" => "calc(var(--radius) - 2px)",
          "lg" => "var(--radius)",
          "xl" => "calc(var(--radius) + 4px)"
        }.freeze

        ARTIFACTS = ["tokens/tokens.css", "tokens/tailwind-theme.css", "DESIGN.md"].freeze

        def initialize(tokens: Tokens.load, root: Poetry::Core.root)
          @tokens = tokens
          @root = Pathname.new(root)
        end

        def tokens_css
          lines = ["/* #{HEADER} */", "", ":root {", "  --radius: #{@tokens.radius_css};"]
          @tokens.color_names("light").each do |name|
            lines << "  --#{name}: #{@tokens.color("light", name).css};"
          end
          lines << "}" << "" << ".dark {"
          @tokens.color_names("dark").each do |name|
            lines << "  --#{name}: #{@tokens.color("dark", name).css};"
          end
          lines << "}"
          "#{lines.join("\n")}\n"
        end

        def tailwind_theme_css
          lines = ["/* #{HEADER} */", "", "@theme inline {"]
          RADIUS_SCALE.each { |step, value| lines << "  --radius-#{step}: #{value};" }
          @tokens.color_names("light").each do |name|
            lines << "  --color-#{name}: var(--#{name});"
          end
          lines << "}"
          "#{lines.join("\n")}\n"
        end

        def design_md
          "#{front_matter}#{design_md_body}"
        end

        # Regenerates all artifacts on disk. Returns the written paths.
        def generate!
          artifact_contents.map do |relative, content|
            path = @root.join(relative)
            path.dirname.mkpath
            path.write(content)
            relative
          end
        end

        # Relative paths whose on-disk content does not match a fresh
        # generation (missing or stale). Empty means no drift.
        def verify
          artifact_contents.filter_map do |relative, content|
            path = @root.join(relative)
            relative unless path.exist? && path.read == content
          end
        end

        private

        def artifact_contents
          {
            "tokens/tokens.css" => tokens_css,
            "tokens/tailwind-theme.css" => tailwind_theme_css,
            "DESIGN.md" => design_md
          }
        end

        # The machine-readable half of DESIGN.md: exact tokens + the contrast
        # policy, regenerated on every pass. The prose constitution below the
        # front matter is human/agent-authored and preserved verbatim.
        def front_matter
          gate = ContrastGate.new(@tokens)
          data = {
            "design_system" => "poetry",
            "source" => Tokens::DEFAULT_RELATIVE_PATH,
            "generator" => "bin/rake tokens:generate",
            "dark_mode" => "class.dark ",
            "radius" => @tokens.radius_css,
            "radius_scale" => RADIUS_SCALE.transform_keys { |k| "radius-#{k}" },
            "colors" => @tokens.modes.to_h do |mode|
              [mode, @tokens.color_names(mode).to_h { |n| [n, @tokens.color(mode, n).css] }]
            end,
            "contrast_policy" => {
              "floor" => "WCAG 2.2 AA (4.5:1) - locked, every gated pair ",
              "target" => "AAA (7:1) wherever achievable at lock time",
              "gate" => "Poetry::Core::Tokens::ContrastGate (CI: rake test)",
              "aa_exceptions" => gate.results.select { |r| r.lock == :aa }.map(&:to_s)
            },
            "parity" => {
              "base" => "shadcn/ui v4 neutral (cssVarsV4 drop-in var set)",
              "deltas" => PARITY_DELTAS
            }
          }
          "#{YAML.dump(data)}---\n"
        end

        def design_md_body
          existing = @root.join("DESIGN.md")
          if existing.exist? && (body = existing.read[/\A---\n.*?\n---\n(.*)\z/m, 1])
            body
          else
            STARTER_BODY
          end
        end

        STARTER_BODY = <<~BODY

          # DESIGN.md - the poetry design constitution

          The front matter above is **generated** from `tokens/tokens.dtcg.json`
          (`bin/rake tokens:generate`) and lists the exact tokens; this body is the
          judgment layer - edit it freely, it is preserved across regenerations.

          ## Principles

          - **Semantic roles only.** Components consume role tokens (`primary`,
            `destructive`, `muted`, `accent`, ...) - never raw palette values, never
            hex/oklch literals in markup (enforced by the class Verifier).
          - **Both modes always.** Every surface must hold in light and dark; dark
            mode is the `.dark` class convention, and the contrast gate
            asserts every pair in both modes.
          - **Contrast is law, not taste.** WCAG 2.2 AA is a locked floor; AAA is
            enforced where achievable. Exceptions are explicit (front matter) and
            reviewed - never silent.
          - **Re-skin at the source.** Restyling the system means editing the DTCG
            tokens (or dropping in a shadcn v4 theme over `tokens/tokens.css`) and
            regenerating - one source, every surface.

          ## Do / Don't

          - Do pick variants by intent (one `primary` action per view; `destructive`
            only for irreversible actions).
          - Do keep borders subtle (`border`/`input` are deliberately low-contrast;
            they are not text and are not gated as text).
          - Don't paint white text on solid `destructive` in dark mode - dark
            destructive surfaces are rendered at 60% over the background (2.9:1
            solid vs 6.5:1 composited).
          - Don't introduce new colors, shadows, or radii without adding tokens
            here first.
        BODY
        private_constant :STARTER_BODY
      end
    end
  end
end
